DROP DATABASE IF EXISTS relevant;
CREATE DATABASE relevant;

USE relevant;

CREATE TABLE games (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  release_date TEXT NOT NULL,
  price INTEGER NOT NULL,
  average_review TEXT NOT NULL,
  thumbnail TEXT NOT NULL
);

CREATE TABLE genres (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name TEXT NOT NULL
);

CREATE TABLE link (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  genreId INTEGER NOT NULL,
  gameId INTEGER NOT NULL
);

ALTER TABLE link ADD FOREIGN KEY (genreId) REFERENCES genres (id);
ALTER TABLE link ADD FOREIGN KEY (gameId) REFERENCES games (id);